# Generated by Django 4.2.1 on 2023-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_notification_admin_mine_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Notification',
            new_name='Admine_mine_Notification',
        ),
    ]
