# Generated by Django 4.2.1 on 2023-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_staff_notification_admine_mine_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Lucky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_one', models.IntegerField()),
                ('time', models.CharField(max_length=60)),
                ('max_man', models.CharField(max_length=60)),
                ('prize_two', models.IntegerField()),
                ('prize_three', models.IntegerField()),
            ],
        ),
    ]
